### PR TITLE
S71500 update/v3 0

### LINKED ISSUE #14: RequestFactory: Enhance consistency and provide more services
GetPlcProgramHandler => GetApiPlcProgramHandler

Also provide GetService method for services that do not need parameters currently
=> GetApiWebAppResourceBuilder
=> GetApiWebAppDataSaver

Maybe also:
=> GetApiWebAppConfigParser(parameters)
=> GetGuidGenerator(parameters)
=> GetCharSetIdGenerator(parameters)
=> GetResponsechecker...
=> GetRequestFactory()?
...

### LINKED ISSUE #22: S7-1500 Firmware Version V3.0 Library Update
As a Library user I want to be able to use the new API methods introduced with the S7-1500 PLC Firmware version V3.0.
A list of the method follows, also a little list of comfort methods we want to provide.

### PR DESCRIPTION
**Pull request by KircMax**
New Methods to support:
- [x] DataLogs.DownloadAndClear
- [x] Files.Browse
- [x] Files.Create
- [x] Files.CreateDirectory
- [x] Files.Delete
- [x] Files.DeleteDirectory
- [x] Files.Download
- [x] Files.Rename
- [x] Plc.CreateBackup
- [x] Plc.ReadSystemTime
- [x] Plc.ReadTimeSettings
- [x] Plc.RestoreBackup

New Comfort Methods to provide:
- [x]  DirectoryBuilder
- [x]  DirectoryHandler
- [x]  FileHandler
- [x]  FileResourceBuilder
- [x]  TicketHandler

closes #22 
closes #14

### CODE REVIEW

**Comment by PTKu** [comment]
Great job @KircMax! One question. Will it be possible to use it alternatively between v2 and v3, based on the version of the target system?

**Comment by KircMax** [comment]
Thanks @PTKu.
I am not sure what exactly you mean by the question... 
So far I have no checks in place for the comfort method wether or not they are expected to be available on the given target system (like the file API Methods to be in place to be able to use the ApiFileHandler etc.)...
I also - so far - wouldn't plan on doing so, normally they should just throw the Method Not Found Exception like the PLC will answer (I think this is fine)...
But the RequestHandler and thereby the other Comfort "Extensions" using it will work just fine on any plc that implements the features => Deploying a WebApp will work on a plc with V2.9 just like on a plc with V3.0 so the newest library version can always be used (and should always be usable) with any plc firmware version... 
Does this answer your question?

**Comment by PTKu** [comment]
> Thanks @PTKu. I am not sure what exactly you mean by the question... So far I have no checks in place for the comfort method wether or not they are expected to be available on the given target system (like the file API Methods to be in place to be able to use the ApiFileHandler etc.)... I also - so far - wouldn't plan on doing so, normally they should just throw the Method Not Found Exception like the PLC will answer (I think this is fine)... But the RequestHandler and thereby the other Comfort "Extensions" using it will work just fine on any plc that implements the features => Deploying a WebApp will work on a plc with V2.9 just like on a plc with V3.0 so the newest library version can always be used (and should always be usable) with any plc firmware version... Does this answer your question?

Sorry for not being more specific. Yes, it does answer my question. Will give it a try as soon as you release it! 😉

**Comment by KircMax** [comment]
@PTKu have fun trying it out 👍 
If you face any issues please feel free to reach out!

**Pull request merged**
