### PR TITLE
Added .net6.0 & .net7.0 target frameworks & update to latest packages.

### PR DESCRIPTION
**Pull request by PTKu**
Just added the framework targets net6.0 because LTS net7.0 because latest.

In order to make the things work without certificate in .net6.0 and greater added a static class providing the certificate handling for those targets (readme additions for that too).

Some test resulting in inconclusive after general package update to latest from NuGet.org passing on my end, did some integration testing against real hardware as well.

Is the singing of the [contributing](https://github.com/siemens/simatic-s7-webserver-api/blob/de4e27d895f5983c096103f0957eb843a32994cb/CONTRIBUTING.md) document compulsory? 

If so, who do I send it to.

### CODE REVIEW

**Comment by KircMax** [comment]
Thanks a lot for contributing! 
Thanks also for signing the CLA :).

**Comment by KircMax** [comment]
image

**Comment by PTKu** [comment]
> image

The pipeline will need to use .net7.0 SDK for `build` and `test` instead of .NET Core 3.1, since added new targets.

**Comment by PTKu** [comment]
Fixed line ending to reduce number of changes.

**Pull request merged**
